### ISSUE TITLE
Improve log messages

### ISSUE THREAD

**Issue by ThomasCrvsr** [ThomasCrvsr/bower-check-conflicts#8]
* Precise which deps uses the dep related to the conflict
ex : 
<pre>
<code>
non-persisted conflict about underscore:
   |- installed version : 1.0.0
   |- required version :
       |- backbone : ~1.7.0
       |- underscore: ~1.5.0
</code>
</pre>
* Precise when the installed version of the dep does not correspond to the resolved one
<pre>
<code>
wrong installed version of underscore:
   |- installed version : 1.0.0
   |- resolved version : 1.6.0
</code>
</pre>

**Comment by SiegfriedEhret** [comment]
:+1:
